name: Django Migrate

on:
  push:
    branches: ["main"]
    paths:
      - 'backend/**'

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run makemigrations
        run: |
          cd backend
          python manage.py makemigrations

      - name: Run migrate
        run: |
          cd backend
          python manage.py migrate